/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.fix[_ngcontent-%COMP%] {\r\n  height: 53px;\r\n  width: 250px;\r\n  color: #fff !important;\r\n  text-align: center;\r\n  padding: 11px;\r\n  font-size: 20px;\r\n}\r\n.align-center-flex[_ngcontent-%COMP%] {\r\n  height: 100%;\r\n  width: 100%;\r\n  display: flex;\r\n  text-align: center;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  align-content: center;\r\n  align-self: center;\r\n  justify-content: center;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL29yZGVyLXN1Y2Nzcy9vcmRlci1zdWNjc3MuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9vcmdhbmljLXNob3AtbWFzdGVyL29yZ2FuaWMtc2hvcC9zcmMvYXBwL3Nob3BwaW5nL2NvbXBvbmVudHMvb3JkZXItc3VjY3NzL29yZGVyLXN1Y2Nzcy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
