/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.btn-login[_ngcontent-%COMP%] {\r\n  height: 53px;\r\n  width: 250px;\r\n  font-size: 16px;\r\n}\r\n\r\n.align-center-flex[_ngcontent-%COMP%] {\r\n  height: 100%;\r\n  width: 100%;\r\n  display: flex;\r\n  text-align: center;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  align-content: center;\r\n  align-self: center;\r\n  justify-content: center;\r\n}\r\n\r\nbody[_ngcontent-%COMP%] {\r\n  padding: 2em;\r\n}\r\n\r\n.facebook[_ngcontent-%COMP%] {\r\n  background-color: #4C69BA;\r\n  background-image: linear-gradient(#4C69BA, #3B55A0);\r\n  outline: none;\r\n}\r\n\r\n.facebook[_ngcontent-%COMP%]:hover, .facebook[_ngcontent-%COMP%]:focus {\r\n  background-color: #5B7BD5;\r\n  background-image: linear-gradient(#5B7BD5, #4864B1);\r\n}\r\n\r\n.google[_ngcontent-%COMP%] {\r\n  background: #DD4B39;\r\n  background-image: linear-gradient(#DD4B39, #c21a07);\r\n}\r\n\r\n.google[_ngcontent-%COMP%]:hover, .google[_ngcontent-%COMP%]:focus {\r\n  background: #E74B37;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9jb3JlL2NvbXBvbmVudHMvbG9naW4vbG9naW4uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9vcmdhbmljLXNob3AtbWFzdGVyL29yZ2FuaWMtc2hvcC9zcmMvYXBwL2NvcmUvY29tcG9uZW50cy9sb2dpbi9sb2dpbi5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
