/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.sticky-top[_ngcontent-%COMP%] {\r\n  top: 80px;\r\n  margin-bottom: 20px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL3Byb2R1Y3RzL3Byb2R1Y3QtZmlsdGVyL3Byb2R1Y3QtZmlsdGVyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL3Byb2R1Y3RzL3Byb2R1Y3QtZmlsdGVyL3Byb2R1Y3QtZmlsdGVyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
