/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './admin-orders.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../shared/components/list-order-view/list-order-view.component.ngfactory';
import * as i3 from '../../../shared/components/list-order-view/list-order-view.component';
import * as i4 from './admin-orders.component';
import * as i5 from '../../../shared/services/order.service';
const styles_AdminOrdersComponent:any[] = [i0.styles];
export const RenderType_AdminOrdersComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AdminOrdersComponent,data:{}});
export function View_AdminOrdersComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['All Orders - Admin'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'list-order-view',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_ListOrderViewComponent_0,
      i2.RenderType_ListOrderViewComponent)),i1.ɵdid(114688,(null as any),0,i3.ListOrderViewComponent,
      ([] as any[]),{order$:[0,'order$']},(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n']))],(_ck,_v) => {
    var _co:i4.AdminOrdersComponent = _v.component;
    const currVal_0:any = _co.order$;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_AdminOrdersComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-admin-orders',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdminOrdersComponent_0,
      RenderType_AdminOrdersComponent)),i1.ɵdid(114688,(null as any),0,i4.AdminOrdersComponent,
      [i5.OrderService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdminOrdersComponentNgFactory:i1.ComponentFactory<i4.AdminOrdersComponent> = i1.ɵccf('app-admin-orders',
    i4.AdminOrdersComponent,View_AdminOrdersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hZG1pbi9jb21wb25lbnRzL2FkbWluLW9yZGVycy9hZG1pbi1vcmRlcnMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvYWRtaW4vY29tcG9uZW50cy9hZG1pbi1vcmRlcnMvYWRtaW4tb3JkZXJzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvYWRtaW4vY29tcG9uZW50cy9hZG1pbi1vcmRlcnMvYWRtaW4tb3JkZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hZG1pbi9jb21wb25lbnRzL2FkbWluLW9yZGVycy9hZG1pbi1vcmRlcnMuY29tcG9uZW50LnRzLkFkbWluT3JkZXJzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkFsbCBPcmRlcnMgLSBBZG1pbjwvaDE+XHJcblxyXG48bGlzdC1vcmRlci12aWV3IFtvcmRlciRdPVwib3JkZXIkXCI+PC9saXN0LW9yZGVyLXZpZXc+XHJcbiIsIjxhcHAtYWRtaW4tb3JkZXJzPjwvYXBwLWFkbWluLW9yZGVycz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLHdDQUF1QjtNQUFBLFdBRTNCO01BQUE7MENBQUEsVUFBQTtNQUFBLG1EQUFxRDtNQUFBOztJQUFwQztJQUFqQixXQUFpQixTQUFqQjs7OztvQkNGQTtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
