/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './my-orders.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../shared/components/list-order-view/list-order-view.component.ngfactory';
import * as i3 from '../../../shared/components/list-order-view/list-order-view.component';
import * as i4 from './my-orders.component';
import * as i5 from '../../../shared/services/auth.service';
import * as i6 from '../../../shared/services/order.service';
const styles_MyOrdersComponent:any[] = [i0.styles];
export const RenderType_MyOrdersComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MyOrdersComponent,data:{}});
export function View_MyOrdersComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['All Orders'])),(_l()(),i1.ɵted((null as any),['\n\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'list-order-view',([] as any[]),
          (null as any),(null as any),(null as any),i2.View_ListOrderViewComponent_0,
          i2.RenderType_ListOrderViewComponent)),i1.ɵdid(114688,(null as any),0,i3.ListOrderViewComponent,
          ([] as any[]),{order$:[0,'order$']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i4.MyOrdersComponent = _v.component;
    const currVal_0:any = _co.order$;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_MyOrdersComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-my-orders',
      ([] as any[]),(null as any),(null as any),(null as any),View_MyOrdersComponent_0,
      RenderType_MyOrdersComponent)),i1.ɵdid(114688,(null as any),0,i4.MyOrdersComponent,
      [i5.AuthService,i6.OrderService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MyOrdersComponentNgFactory:i1.ComponentFactory<i4.MyOrdersComponent> = i1.ɵccf('app-my-orders',
    i4.MyOrdersComponent,View_MyOrdersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL215LW9yZGVycy9teS1vcmRlcnMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvc2hvcHBpbmcvY29tcG9uZW50cy9teS1vcmRlcnMvbXktb3JkZXJzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvc2hvcHBpbmcvY29tcG9uZW50cy9teS1vcmRlcnMvbXktb3JkZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL215LW9yZGVycy9teS1vcmRlcnMuY29tcG9uZW50LnRzLk15T3JkZXJzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkFsbCBPcmRlcnM8L2gxPlxyXG5cclxuPGxpc3Qtb3JkZXItdmlldyBbb3JkZXIkXT1cIm9yZGVyJFwiPjwvbGlzdC1vcmRlci12aWV3PlxyXG4iLCI8YXBwLW15LW9yZGVycz48L2FwcC1teS1vcmRlcnM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUEsZ0NBQWU7TUFFbkI7VUFBQTs4Q0FBQSxVQUFBO1VBQUEsbURBQXFEO1VBQUE7O0lBQXBDO0lBQWpCLFdBQWlCLFNBQWpCOzs7O29CQ0ZBO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
