/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.flex-center-align[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    align-items: center;\r\n    align-self: center;\r\n    align-items: center;\r\n    justify-content: center;\r\n    height: 100%;\r\n    width: 100%;\r\n}\r\n\r\n@media(max-width: 500px) {\r\n    .sm-setup[_ngcontent-%COMP%] {\r\n        width: 100%;\r\n        padding: 0 25px;\r\n        margin: 0 25px;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaGFyZWQvY29tcG9uZW50cy9wcm9kdWN0LXF1YW50aXR5L3Byb2R1Y3QtcXVhbnRpdHkuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9vcmdhbmljLXNob3AtbWFzdGVyL29yZ2FuaWMtc2hvcC9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnRzL3Byb2R1Y3QtcXVhbnRpdHkvcHJvZHVjdC1xdWFudGl0eS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
