/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i4 from '../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i5 from '../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i6 from '../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i7 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i8 from '../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i9 from '../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i10 from './core/components/login/login.component.ngfactory';
import * as i11 from './admin/components/admin-orders/admin-orders.component.ngfactory';
import * as i12 from './admin/components/product-form/product-form.component.ngfactory';
import * as i13 from './admin/components/admin-products/admin-products.component.ngfactory';
import * as i14 from './shopping/components/shoping-cart/shoping-cart.component.ngfactory';
import * as i15 from './shopping/components/products/products.component.ngfactory';
import * as i16 from './shopping/components/my-orders/my-orders.component.ngfactory';
import * as i17 from './shopping/components/check-out/check-out.component.ngfactory';
import * as i18 from './shopping/components/order-succss/order-succss.component.ngfactory';
import * as i19 from './shopping/components/order-view/order-view.component.ngfactory';
import * as i20 from './app.component.ngfactory';
import * as i21 from '@angular/common';
import * as i22 from '@angular/platform-browser';
import * as i23 from 'angularfire2';
import * as i24 from '@angular/forms';
import * as i25 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i26 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i27 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i28 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i29 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i30 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i31 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i32 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i33 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i34 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i35 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i36 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i37 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i38 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i39 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i40 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i41 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i42 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i43 from 'angularfire2/auth';
import * as i44 from 'angularfire2/database';
import * as i45 from './shared/services/user.service';
import * as i46 from './shared/services/auth.service';
import * as i47 from './shared/services/auth-guard.service';
import * as i48 from '@angular/router';
import * as i49 from './shared/services/category.service';
import * as i50 from './shared/services/product.service';
import * as i51 from './shared/services/shopping-cart.service';
import * as i52 from './shared/services/order.service';
import * as i53 from './admin/services/admin-auth-guard.service';
import * as i54 from './core/components/login/login.component';
import * as i55 from './admin/components/admin-orders/admin-orders.component';
import * as i56 from './admin/components/product-form/product-form.component';
import * as i57 from './admin/components/admin-products/admin-products.component';
import * as i58 from './shopping/components/shoping-cart/shoping-cart.component';
import * as i59 from './shopping/components/products/products.component';
import * as i60 from './shopping/components/my-orders/my-orders.component';
import * as i61 from './shopping/components/check-out/check-out.component';
import * as i62 from './shopping/components/order-succss/order-succss.component';
import * as i63 from './shopping/components/order-view/order-view.component';
import * as i64 from 'ng2-validation/dist/index';
import * as i65 from 'angular-4-data-table/src/index';
import * as i66 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i67 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i68 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i69 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i70 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i71 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i72 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i73 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i74 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i75 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i76 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i77 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i78 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i79 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i80 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i81 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i82 from '@ng-bootstrap/ng-bootstrap/index';
import * as i83 from './shared/shared.module';
import * as i84 from './core/core.module';
import * as i85 from './admin/admin.module';
import * as i86 from './shopping/shopping.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.NgbAlertNgFactory,i4.NgbTooltipWindowNgFactory,i5.NgbTypeaheadWindowNgFactory,
              i6.NgbDatepickerNgFactory,i7.NgbModalBackdropNgFactory,i8.NgbModalWindowNgFactory,
              i9.NgbPopoverWindowNgFactory,i10.LoginComponentNgFactory,i11.AdminOrdersComponentNgFactory,
              i12.ProductFormComponentNgFactory,i13.AdminProductsComponentNgFactory,
              i14.ShopingCartComponentNgFactory,i15.ProductsComponentNgFactory,i16.MyOrdersComponentNgFactory,
              i17.CheckOutComponentNgFactory,i18.OrderSuccssComponentNgFactory,i19.OrderViewComponentNgFactory,
              i20.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i21.NgLocalization,
              i21.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i22.DomSanitizer,
              i22.ɵe,[i21.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i22.DomSanitizer]),
          i0.ɵmpd(4608,i22.HAMMER_GESTURE_CONFIG,i22.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i22.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i22.ɵDomEventsPlugin(p0_0),new i22.ɵKeyEventsPlugin(p1_0),
                new i22.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i21.DOCUMENT,i21.DOCUMENT,i21.DOCUMENT,i22.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i22.EventManager,i22.EventManager,[i22.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i22.ɵDomSharedStylesHost,i22.ɵDomSharedStylesHost,[i21.DOCUMENT]),
          i0.ɵmpd(4608,i22.ɵDomRendererFactory2,i22.ɵDomRendererFactory2,[i22.EventManager,
              i22.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i22.ɵDomRendererFactory2]),i0.ɵmpd(6144,i22.ɵSharedStylesHost,(null as any),
              [i22.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i22.Meta,i22.Meta,[i21.DOCUMENT]),i0.ɵmpd(4608,
              i22.Title,i22.Title,[i21.DOCUMENT]),i0.ɵmpd(5120,i23.FirebaseApp,i23.ɵa,
              [i23.FirebaseAppConfigToken,i23.FirebaseAppName]),i0.ɵmpd(4608,i24.ɵi,
              i24.ɵi,([] as any[])),i0.ɵmpd(4608,i25.NgbModalStack,i25.NgbModalStack,
              [i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),i0.ɵmpd(4608,
              i26.NgbModal,i26.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,i25.NgbModalStack]),
          i0.ɵmpd(4608,i27.NgbAlertConfig,i27.NgbAlertConfig,([] as any[])),i0.ɵmpd(4608,
              i28.NgbProgressbarConfig,i28.NgbProgressbarConfig,([] as any[])),i0.ɵmpd(4608,
              i29.NgbTooltipConfig,i29.NgbTooltipConfig,([] as any[])),i0.ɵmpd(4608,
              i30.NgbTypeaheadConfig,i30.NgbTypeaheadConfig,([] as any[])),i0.ɵmpd(4608,
              i31.NgbAccordionConfig,i31.NgbAccordionConfig,([] as any[])),i0.ɵmpd(4608,
              i32.NgbCarouselConfig,i32.NgbCarouselConfig,([] as any[])),i0.ɵmpd(4608,
              i33.NgbCalendar,i33.NgbCalendarGregorian,([] as any[])),i0.ɵmpd(4608,
              i34.NgbDatepickerI18n,i34.NgbDatepickerI18nDefault,([] as any[])),i0.ɵmpd(4608,
              i35.NgbDateParserFormatter,i35.NgbDateISOParserFormatter,([] as any[])),
          i0.ɵmpd(4608,i36.NgbDatepickerConfig,i36.NgbDatepickerConfig,([] as any[])),
          i0.ɵmpd(4608,i37.NgbDropdownConfig,i37.NgbDropdownConfig,([] as any[])),
          i0.ɵmpd(4608,i38.NgbPaginationConfig,i38.NgbPaginationConfig,([] as any[])),
          i0.ɵmpd(4608,i39.NgbPopoverConfig,i39.NgbPopoverConfig,([] as any[])),i0.ɵmpd(4608,
              i40.NgbRatingConfig,i40.NgbRatingConfig,([] as any[])),i0.ɵmpd(4608,
              i41.NgbTabsetConfig,i41.NgbTabsetConfig,([] as any[])),i0.ɵmpd(4608,
              i42.NgbTimepickerConfig,i42.NgbTimepickerConfig,([] as any[])),i0.ɵmpd(5120,
              i43.AngularFireAuth,i43._getAngularFireAuth,[i23.FirebaseApp]),i0.ɵmpd(5120,
              i44.AngularFireDatabase,i44._getAngularFireDatabase,[i23.FirebaseApp]),
          i0.ɵmpd(4608,i45.UserService,i45.UserService,[i44.AngularFireDatabase]),
          i0.ɵmpd(4608,i46.AuthService,i46.AuthService,[i45.UserService,i43.AngularFireAuth]),
          i0.ɵmpd(4608,i47.AuthGuardService,i47.AuthGuardService,[i46.AuthService,
              i48.Router]),i0.ɵmpd(4608,i49.CategoryService,i49.CategoryService,[i44.AngularFireDatabase]),
          i0.ɵmpd(4608,i50.ProductService,i50.ProductService,[i44.AngularFireDatabase]),
          i0.ɵmpd(4608,i51.ShoppingCartService,i51.ShoppingCartService,[i44.AngularFireDatabase]),
          i0.ɵmpd(4608,i52.OrderService,i52.OrderService,[i44.AngularFireDatabase,
              i51.ShoppingCartService]),i0.ɵmpd(4608,i53.AdminAuthGuardService,i53.AdminAuthGuardService,
              [i46.AuthService,i45.UserService,i48.Router]),i0.ɵmpd(5120,i48.ActivatedRoute,
              i48.ɵf,[i48.Router]),i0.ɵmpd(4608,i48.NoPreloading,i48.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i48.PreloadingStrategy,(null as any),[i48.NoPreloading]),
          i0.ɵmpd(135680,i48.RouterPreloader,i48.RouterPreloader,[i48.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i48.PreloadingStrategy]),i0.ɵmpd(4608,i48.PreloadAllModules,
              i48.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i48.ROUTER_INITIALIZER,
              i48.ɵi,[i48.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i48.ROUTER_INITIALIZER]),i0.ɵmpd(512,i21.CommonModule,i21.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i22.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i48.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i48.ɵg,i48.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i22.ɵc(p0_0,p0_1),i48.ɵh(p1_0)];
              },[[2,i22.NgProbeToken],[2,i0.NgProbeToken],i48.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i22.BrowserModule,i22.BrowserModule,[[3,i22.BrowserModule]]),
          i0.ɵmpd(512,i23.AngularFireModule,i23.AngularFireModule,([] as any[])),i0.ɵmpd(1024,
              i48.ɵa,i48.ɵd,[[3,i48.Router]]),i0.ɵmpd(512,i48.UrlSerializer,i48.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i48.ChildrenOutletContexts,i48.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i48.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i21.LocationStrategy,i48.ɵc,[i21.PlatformLocation,[2,i21.APP_BASE_HREF],
              i48.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i21.Location,i21.Location,[i21.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i48.ROUTES,() => {
            return [[{path:'login',component:i54.LoginComponent}],[{path:'admin/orders',
                component:i55.AdminOrdersComponent,canActivate:[i47.AuthGuardService,
                    i53.AdminAuthGuardService]},{path:'admin/products/new',component:i56.ProductFormComponent,
                canActivate:[i47.AuthGuardService,i53.AdminAuthGuardService]},{path:'admin/products/:id',
                component:i56.ProductFormComponent,canActivate:[i47.AuthGuardService,
                    i53.AdminAuthGuardService]},{path:'admin/products',component:i57.AdminProductsComponent,
                canActivate:[i47.AuthGuardService,i53.AdminAuthGuardService]}],[{path:'cart',
                component:i58.ShopingCartComponent},{path:'Products',component:i59.ProductsComponent},
                {path:'myorders',component:i60.MyOrdersComponent,canActivate:[i47.AuthGuardService]},
                {path:'checkout',component:i61.CheckOutComponent,canActivate:[i47.AuthGuardService]},
                {path:'order-success/:id',component:i62.OrderSuccssComponent,canActivate:[i47.AuthGuardService]},
                {path:'order-details/:id',component:i63.OrderViewComponent,canActivate:[i47.AuthGuardService]}],
                [{path:'',component:i59.ProductsComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i48.Router,i48.ɵe,[i0.ApplicationRef,i48.UrlSerializer,
              i48.ChildrenOutletContexts,i21.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i48.ROUTES,i48.ROUTER_CONFIGURATION,[2,i48.UrlHandlingStrategy],
              [2,i48.RouteReuseStrategy]]),i0.ɵmpd(512,i48.RouterModule,i48.RouterModule,
              [[2,i48.ɵa],[2,i48.Router]]),i0.ɵmpd(512,i24.ɵba,i24.ɵba,([] as any[])),
          i0.ɵmpd(512,i24.FormsModule,i24.FormsModule,([] as any[])),i0.ɵmpd(512,i64.CustomFormsModule,
              i64.CustomFormsModule,([] as any[])),i0.ɵmpd(512,i65.DataTableModule,
              i65.DataTableModule,([] as any[])),i0.ɵmpd(512,i66.NgbAlertModule,i66.NgbAlertModule,
              ([] as any[])),i0.ɵmpd(512,i67.NgbButtonsModule,i67.NgbButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i68.NgbCollapseModule,i68.NgbCollapseModule,
              ([] as any[])),i0.ɵmpd(512,i69.NgbProgressbarModule,i69.NgbProgressbarModule,
              ([] as any[])),i0.ɵmpd(512,i70.NgbTooltipModule,i70.NgbTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i71.NgbTypeaheadModule,i71.NgbTypeaheadModule,
              ([] as any[])),i0.ɵmpd(512,i72.NgbAccordionModule,i72.NgbAccordionModule,
              ([] as any[])),i0.ɵmpd(512,i73.NgbCarouselModule,i73.NgbCarouselModule,
              ([] as any[])),i0.ɵmpd(512,i74.NgbDatepickerModule,i74.NgbDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i75.NgbDropdownModule,i75.NgbDropdownModule,
              ([] as any[])),i0.ɵmpd(512,i76.NgbModalModule,i76.NgbModalModule,([] as any[])),
          i0.ɵmpd(512,i77.NgbPaginationModule,i77.NgbPaginationModule,([] as any[])),
          i0.ɵmpd(512,i78.NgbPopoverModule,i78.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,
              i79.NgbRatingModule,i79.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i80.NgbTabsetModule,
              i80.NgbTabsetModule,([] as any[])),i0.ɵmpd(512,i81.NgbTimepickerModule,
              i81.NgbTimepickerModule,([] as any[])),i0.ɵmpd(512,i82.NgbRootModule,
              i82.NgbRootModule,([] as any[])),i0.ɵmpd(512,i43.AngularFireAuthModule,
              i43.AngularFireAuthModule,([] as any[])),i0.ɵmpd(512,i44.AngularFireDatabaseModule,
              i44.AngularFireDatabaseModule,([] as any[])),i0.ɵmpd(512,i83.SharedModule,
              i83.SharedModule,([] as any[])),i0.ɵmpd(512,i84.CoreModule,i84.CoreModule,
              ([] as any[])),i0.ɵmpd(512,i85.AdminModule,i85.AdminModule,([] as any[])),
          i0.ɵmpd(512,i86.ShoppingModule,i86.ShoppingModule,([] as any[])),i0.ɵmpd(512,
              i1.AppModule,i1.AppModule,([] as any[])),i0.ɵmpd(256,i23.FirebaseAppConfigToken,
              {},([] as any[])),i0.ɵmpd(256,i23.FirebaseAppName,(undefined as any),
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
