/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './core/components/bs-navbar/bs-navbar.component.ngfactory';
import * as i3 from './core/components/bs-navbar/bs-navbar.component';
import * as i4 from './shared/services/shopping-cart.service';
import * as i5 from './shared/services/auth.service';
import * as i6 from '@angular/router';
import * as i7 from './app.component';
import * as i8 from './shared/services/user.service';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'bs-navbar',([] as any[]),(null as any),(null as any),(null as any),
      i2.View_BsNavbarComponent_0,i2.RenderType_BsNavbarComponent)),i1.ɵdid(114688,
      (null as any),0,i3.BsNavbarComponent,[i4.ShoppingCartService,i5.AuthService],
      (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','container']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n    '])),(_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i6.RouterOutlet,[i6.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,7,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i7.AppComponent,[i5.AuthService,i8.UserService,
          i6.ActivatedRoute,i6.Router],(null as any),(null as any))],(null as any),
      (null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i7.AppComponent> = i1.ɵccf('app-root',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxyXG48YnMtbmF2YmFyPjwvYnMtbmF2YmFyPlxyXG5cclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG48L2Rpdj5cclxuIiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHVDQUNBO01BQUE7aUVBQUEsVUFBQTtNQUFBO01BQUEsNkJBQXVCLHlDQUV2QjthQUFBO1VBQUEsMERBQXVCO01BQUEsYUFDbkI7TUFBQTthQUFBO3NDQUFBO1VBQUEsZUFBK0IsdUNBQzdCO1VBQUE7SUFKTjtJQUdJOzs7O29CQ0pKO01BQUE7YUFBQTtxQ0FBQTs7OzsifQ==
