/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './shopping.module';
import * as i2 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i3 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i4 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i5 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i6 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i7 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i8 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i9 from './components/shoping-cart/shoping-cart.component.ngfactory';
import * as i10 from './components/products/products.component.ngfactory';
import * as i11 from './components/my-orders/my-orders.component.ngfactory';
import * as i12 from './components/check-out/check-out.component.ngfactory';
import * as i13 from './components/order-succss/order-succss.component.ngfactory';
import * as i14 from './components/order-view/order-view.component.ngfactory';
import * as i15 from '@angular/common';
import * as i16 from '@angular/forms';
import * as i17 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i18 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i19 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i20 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i21 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i22 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i23 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i24 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i25 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i26 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i27 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i28 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i29 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i30 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i31 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i32 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i33 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i34 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i35 from 'angularfire2';
import * as i36 from 'angularfire2/auth';
import * as i37 from 'angularfire2/database';
import * as i38 from '../shared/services/user.service';
import * as i39 from '../shared/services/auth.service';
import * as i40 from '../shared/services/auth-guard.service';
import * as i41 from '@angular/router';
import * as i42 from '../shared/services/category.service';
import * as i43 from '../shared/services/product.service';
import * as i44 from '../shared/services/shopping-cart.service';
import * as i45 from '../shared/services/order.service';
import * as i46 from 'ng2-validation/dist/index';
import * as i47 from 'angular-4-data-table/src/index';
import * as i48 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i49 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i50 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i51 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i52 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i53 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i54 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i55 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i56 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i57 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i58 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i59 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i60 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i61 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i62 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i63 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i64 from '@ng-bootstrap/ng-bootstrap/index';
import * as i65 from '../shared/shared.module';
import * as i66 from './components/shoping-cart/shoping-cart.component';
import * as i67 from './components/products/products.component';
import * as i68 from './components/my-orders/my-orders.component';
import * as i69 from './components/check-out/check-out.component';
import * as i70 from './components/order-succss/order-succss.component';
import * as i71 from './components/order-view/order-view.component';
export const ShoppingModuleNgFactory:i0.NgModuleFactory<i1.ShoppingModule> = i0.ɵcmf(i1.ShoppingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgbAlertNgFactory,i3.NgbTooltipWindowNgFactory,i4.NgbTypeaheadWindowNgFactory,
              i5.NgbDatepickerNgFactory,i6.NgbModalBackdropNgFactory,i7.NgbModalWindowNgFactory,
              i8.NgbPopoverWindowNgFactory,i9.ShopingCartComponentNgFactory,i10.ProductsComponentNgFactory,
              i11.MyOrdersComponentNgFactory,i12.CheckOutComponentNgFactory,i13.OrderSuccssComponentNgFactory,
              i14.OrderViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i15.NgLocalization,i15.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(4608,i16.ɵi,i16.ɵi,([] as any[])),i0.ɵmpd(4608,i17.NgbModalStack,
              i17.NgbModalStack,[i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),
          i0.ɵmpd(4608,i18.NgbModal,i18.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,
              i17.NgbModalStack]),i0.ɵmpd(4608,i19.NgbAlertConfig,i19.NgbAlertConfig,
              ([] as any[])),i0.ɵmpd(4608,i20.NgbProgressbarConfig,i20.NgbProgressbarConfig,
              ([] as any[])),i0.ɵmpd(4608,i21.NgbTooltipConfig,i21.NgbTooltipConfig,
              ([] as any[])),i0.ɵmpd(4608,i22.NgbTypeaheadConfig,i22.NgbTypeaheadConfig,
              ([] as any[])),i0.ɵmpd(4608,i23.NgbAccordionConfig,i23.NgbAccordionConfig,
              ([] as any[])),i0.ɵmpd(4608,i24.NgbCarouselConfig,i24.NgbCarouselConfig,
              ([] as any[])),i0.ɵmpd(4608,i25.NgbCalendar,i25.NgbCalendarGregorian,
              ([] as any[])),i0.ɵmpd(4608,i26.NgbDatepickerI18n,i26.NgbDatepickerI18nDefault,
              ([] as any[])),i0.ɵmpd(4608,i27.NgbDateParserFormatter,i27.NgbDateISOParserFormatter,
              ([] as any[])),i0.ɵmpd(4608,i28.NgbDatepickerConfig,i28.NgbDatepickerConfig,
              ([] as any[])),i0.ɵmpd(4608,i29.NgbDropdownConfig,i29.NgbDropdownConfig,
              ([] as any[])),i0.ɵmpd(4608,i30.NgbPaginationConfig,i30.NgbPaginationConfig,
              ([] as any[])),i0.ɵmpd(4608,i31.NgbPopoverConfig,i31.NgbPopoverConfig,
              ([] as any[])),i0.ɵmpd(4608,i32.NgbRatingConfig,i32.NgbRatingConfig,
              ([] as any[])),i0.ɵmpd(4608,i33.NgbTabsetConfig,i33.NgbTabsetConfig,
              ([] as any[])),i0.ɵmpd(4608,i34.NgbTimepickerConfig,i34.NgbTimepickerConfig,
              ([] as any[])),i0.ɵmpd(5120,i35.FirebaseApp,i35.ɵa,[i35.FirebaseAppConfigToken,
              i35.FirebaseAppName]),i0.ɵmpd(5120,i36.AngularFireAuth,i36._getAngularFireAuth,
              [i35.FirebaseApp]),i0.ɵmpd(5120,i37.AngularFireDatabase,i37._getAngularFireDatabase,
              [i35.FirebaseApp]),i0.ɵmpd(4608,i38.UserService,i38.UserService,[i37.AngularFireDatabase]),
          i0.ɵmpd(4608,i39.AuthService,i39.AuthService,[i38.UserService,i36.AngularFireAuth]),
          i0.ɵmpd(4608,i40.AuthGuardService,i40.AuthGuardService,[i39.AuthService,
              i41.Router]),i0.ɵmpd(4608,i42.CategoryService,i42.CategoryService,[i37.AngularFireDatabase]),
          i0.ɵmpd(4608,i43.ProductService,i43.ProductService,[i37.AngularFireDatabase]),
          i0.ɵmpd(4608,i44.ShoppingCartService,i44.ShoppingCartService,[i37.AngularFireDatabase]),
          i0.ɵmpd(4608,i45.OrderService,i45.OrderService,[i37.AngularFireDatabase,
              i44.ShoppingCartService]),i0.ɵmpd(512,i15.CommonModule,i15.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i41.RouterModule,i41.RouterModule,[[2,i41.ɵa],
              [2,i41.Router]]),i0.ɵmpd(512,i16.ɵba,i16.ɵba,([] as any[])),i0.ɵmpd(512,
              i16.FormsModule,i16.FormsModule,([] as any[])),i0.ɵmpd(512,i46.CustomFormsModule,
              i46.CustomFormsModule,([] as any[])),i0.ɵmpd(512,i47.DataTableModule,
              i47.DataTableModule,([] as any[])),i0.ɵmpd(512,i48.NgbAlertModule,i48.NgbAlertModule,
              ([] as any[])),i0.ɵmpd(512,i49.NgbButtonsModule,i49.NgbButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i50.NgbCollapseModule,i50.NgbCollapseModule,
              ([] as any[])),i0.ɵmpd(512,i51.NgbProgressbarModule,i51.NgbProgressbarModule,
              ([] as any[])),i0.ɵmpd(512,i52.NgbTooltipModule,i52.NgbTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i53.NgbTypeaheadModule,i53.NgbTypeaheadModule,
              ([] as any[])),i0.ɵmpd(512,i54.NgbAccordionModule,i54.NgbAccordionModule,
              ([] as any[])),i0.ɵmpd(512,i55.NgbCarouselModule,i55.NgbCarouselModule,
              ([] as any[])),i0.ɵmpd(512,i56.NgbDatepickerModule,i56.NgbDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i57.NgbDropdownModule,i57.NgbDropdownModule,
              ([] as any[])),i0.ɵmpd(512,i58.NgbModalModule,i58.NgbModalModule,([] as any[])),
          i0.ɵmpd(512,i59.NgbPaginationModule,i59.NgbPaginationModule,([] as any[])),
          i0.ɵmpd(512,i60.NgbPopoverModule,i60.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,
              i61.NgbRatingModule,i61.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i62.NgbTabsetModule,
              i62.NgbTabsetModule,([] as any[])),i0.ɵmpd(512,i63.NgbTimepickerModule,
              i63.NgbTimepickerModule,([] as any[])),i0.ɵmpd(512,i64.NgbRootModule,
              i64.NgbRootModule,([] as any[])),i0.ɵmpd(512,i35.AngularFireModule,i35.AngularFireModule,
              ([] as any[])),i0.ɵmpd(512,i36.AngularFireAuthModule,i36.AngularFireAuthModule,
              ([] as any[])),i0.ɵmpd(512,i37.AngularFireDatabaseModule,i37.AngularFireDatabaseModule,
              ([] as any[])),i0.ɵmpd(512,i65.SharedModule,i65.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.ShoppingModule,i1.ShoppingModule,([] as any[])),i0.ɵmpd(1024,
              i41.ROUTES,() => {
                return [[{path:'cart',component:i66.ShopingCartComponent},{path:'Products',
                    component:i67.ProductsComponent},{path:'myorders',component:i68.MyOrdersComponent,
                    canActivate:[i40.AuthGuardService]},{path:'checkout',component:i69.CheckOutComponent,
                    canActivate:[i40.AuthGuardService]},{path:'order-success/:id',
                    component:i70.OrderSuccssComponent,canActivate:[i40.AuthGuardService]},
                    {path:'order-details/:id',component:i71.OrderViewComponent,canActivate:[i40.AuthGuardService]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9zaG9wcGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9zaG9wcGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
