/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './admin.module';
import * as i2 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i3 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i4 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i5 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i6 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i7 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i8 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i9 from './components/admin-orders/admin-orders.component.ngfactory';
import * as i10 from './components/product-form/product-form.component.ngfactory';
import * as i11 from './components/admin-products/admin-products.component.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/forms';
import * as i14 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i15 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i16 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i17 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i18 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i19 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i20 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i21 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i22 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i23 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i24 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i25 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i26 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i27 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i28 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i29 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i30 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i31 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i32 from 'angularfire2';
import * as i33 from 'angularfire2/auth';
import * as i34 from 'angularfire2/database';
import * as i35 from '../shared/services/user.service';
import * as i36 from '../shared/services/auth.service';
import * as i37 from '../shared/services/auth-guard.service';
import * as i38 from '@angular/router';
import * as i39 from '../shared/services/category.service';
import * as i40 from '../shared/services/product.service';
import * as i41 from '../shared/services/shopping-cart.service';
import * as i42 from '../shared/services/order.service';
import * as i43 from './services/admin-auth-guard.service';
import * as i44 from 'ng2-validation/dist/index';
import * as i45 from 'angular-4-data-table/src/index';
import * as i46 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i47 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i48 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i49 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i50 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i51 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i52 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i53 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i54 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i55 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i56 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i57 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i58 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i59 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i60 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i61 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i62 from '@ng-bootstrap/ng-bootstrap/index';
import * as i63 from '../shared/shared.module';
import * as i64 from './components/admin-orders/admin-orders.component';
import * as i65 from './components/product-form/product-form.component';
import * as i66 from './components/admin-products/admin-products.component';
export const AdminModuleNgFactory:i0.NgModuleFactory<i1.AdminModule> = i0.ɵcmf(i1.AdminModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgbAlertNgFactory,i3.NgbTooltipWindowNgFactory,i4.NgbTypeaheadWindowNgFactory,
              i5.NgbDatepickerNgFactory,i6.NgbModalBackdropNgFactory,i7.NgbModalWindowNgFactory,
              i8.NgbPopoverWindowNgFactory,i9.AdminOrdersComponentNgFactory,i10.ProductFormComponentNgFactory,
              i11.AdminProductsComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i12.NgLocalization,i12.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i13.ɵi,i13.ɵi,([] as any[])),i0.ɵmpd(4608,i14.NgbModalStack,
          i14.NgbModalStack,[i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),
          i0.ɵmpd(4608,i15.NgbModal,i15.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,
              i14.NgbModalStack]),i0.ɵmpd(4608,i16.NgbAlertConfig,i16.NgbAlertConfig,
              ([] as any[])),i0.ɵmpd(4608,i17.NgbProgressbarConfig,i17.NgbProgressbarConfig,
              ([] as any[])),i0.ɵmpd(4608,i18.NgbTooltipConfig,i18.NgbTooltipConfig,
              ([] as any[])),i0.ɵmpd(4608,i19.NgbTypeaheadConfig,i19.NgbTypeaheadConfig,
              ([] as any[])),i0.ɵmpd(4608,i20.NgbAccordionConfig,i20.NgbAccordionConfig,
              ([] as any[])),i0.ɵmpd(4608,i21.NgbCarouselConfig,i21.NgbCarouselConfig,
              ([] as any[])),i0.ɵmpd(4608,i22.NgbCalendar,i22.NgbCalendarGregorian,
              ([] as any[])),i0.ɵmpd(4608,i23.NgbDatepickerI18n,i23.NgbDatepickerI18nDefault,
              ([] as any[])),i0.ɵmpd(4608,i24.NgbDateParserFormatter,i24.NgbDateISOParserFormatter,
              ([] as any[])),i0.ɵmpd(4608,i25.NgbDatepickerConfig,i25.NgbDatepickerConfig,
              ([] as any[])),i0.ɵmpd(4608,i26.NgbDropdownConfig,i26.NgbDropdownConfig,
              ([] as any[])),i0.ɵmpd(4608,i27.NgbPaginationConfig,i27.NgbPaginationConfig,
              ([] as any[])),i0.ɵmpd(4608,i28.NgbPopoverConfig,i28.NgbPopoverConfig,
              ([] as any[])),i0.ɵmpd(4608,i29.NgbRatingConfig,i29.NgbRatingConfig,
              ([] as any[])),i0.ɵmpd(4608,i30.NgbTabsetConfig,i30.NgbTabsetConfig,
              ([] as any[])),i0.ɵmpd(4608,i31.NgbTimepickerConfig,i31.NgbTimepickerConfig,
              ([] as any[])),i0.ɵmpd(5120,i32.FirebaseApp,i32.ɵa,[i32.FirebaseAppConfigToken,
              i32.FirebaseAppName]),i0.ɵmpd(5120,i33.AngularFireAuth,i33._getAngularFireAuth,
              [i32.FirebaseApp]),i0.ɵmpd(5120,i34.AngularFireDatabase,i34._getAngularFireDatabase,
              [i32.FirebaseApp]),i0.ɵmpd(4608,i35.UserService,i35.UserService,[i34.AngularFireDatabase]),
          i0.ɵmpd(4608,i36.AuthService,i36.AuthService,[i35.UserService,i33.AngularFireAuth]),
          i0.ɵmpd(4608,i37.AuthGuardService,i37.AuthGuardService,[i36.AuthService,
              i38.Router]),i0.ɵmpd(4608,i39.CategoryService,i39.CategoryService,[i34.AngularFireDatabase]),
          i0.ɵmpd(4608,i40.ProductService,i40.ProductService,[i34.AngularFireDatabase]),
          i0.ɵmpd(4608,i41.ShoppingCartService,i41.ShoppingCartService,[i34.AngularFireDatabase]),
          i0.ɵmpd(4608,i42.OrderService,i42.OrderService,[i34.AngularFireDatabase,
              i41.ShoppingCartService]),i0.ɵmpd(4608,i43.AdminAuthGuardService,i43.AdminAuthGuardService,
              [i36.AuthService,i35.UserService,i38.Router]),i0.ɵmpd(512,i12.CommonModule,
              i12.CommonModule,([] as any[])),i0.ɵmpd(512,i38.RouterModule,i38.RouterModule,
              [[2,i38.ɵa],[2,i38.Router]]),i0.ɵmpd(512,i13.ɵba,i13.ɵba,([] as any[])),
          i0.ɵmpd(512,i13.FormsModule,i13.FormsModule,([] as any[])),i0.ɵmpd(512,i44.CustomFormsModule,
              i44.CustomFormsModule,([] as any[])),i0.ɵmpd(512,i45.DataTableModule,
              i45.DataTableModule,([] as any[])),i0.ɵmpd(512,i46.NgbAlertModule,i46.NgbAlertModule,
              ([] as any[])),i0.ɵmpd(512,i47.NgbButtonsModule,i47.NgbButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i48.NgbCollapseModule,i48.NgbCollapseModule,
              ([] as any[])),i0.ɵmpd(512,i49.NgbProgressbarModule,i49.NgbProgressbarModule,
              ([] as any[])),i0.ɵmpd(512,i50.NgbTooltipModule,i50.NgbTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i51.NgbTypeaheadModule,i51.NgbTypeaheadModule,
              ([] as any[])),i0.ɵmpd(512,i52.NgbAccordionModule,i52.NgbAccordionModule,
              ([] as any[])),i0.ɵmpd(512,i53.NgbCarouselModule,i53.NgbCarouselModule,
              ([] as any[])),i0.ɵmpd(512,i54.NgbDatepickerModule,i54.NgbDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i55.NgbDropdownModule,i55.NgbDropdownModule,
              ([] as any[])),i0.ɵmpd(512,i56.NgbModalModule,i56.NgbModalModule,([] as any[])),
          i0.ɵmpd(512,i57.NgbPaginationModule,i57.NgbPaginationModule,([] as any[])),
          i0.ɵmpd(512,i58.NgbPopoverModule,i58.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,
              i59.NgbRatingModule,i59.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i60.NgbTabsetModule,
              i60.NgbTabsetModule,([] as any[])),i0.ɵmpd(512,i61.NgbTimepickerModule,
              i61.NgbTimepickerModule,([] as any[])),i0.ɵmpd(512,i62.NgbRootModule,
              i62.NgbRootModule,([] as any[])),i0.ɵmpd(512,i32.AngularFireModule,i32.AngularFireModule,
              ([] as any[])),i0.ɵmpd(512,i33.AngularFireAuthModule,i33.AngularFireAuthModule,
              ([] as any[])),i0.ɵmpd(512,i34.AngularFireDatabaseModule,i34.AngularFireDatabaseModule,
              ([] as any[])),i0.ɵmpd(512,i63.SharedModule,i63.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.AdminModule,i1.AdminModule,([] as any[])),i0.ɵmpd(1024,i38.ROUTES,
              () => {
                return [[{path:'admin/orders',component:i64.AdminOrdersComponent,canActivate:[i37.AuthGuardService,
                    i43.AdminAuthGuardService]},{path:'admin/products/new',component:i65.ProductFormComponent,
                    canActivate:[i37.AuthGuardService,i43.AdminAuthGuardService]},
                    {path:'admin/products/:id',component:i65.ProductFormComponent,
                        canActivate:[i37.AuthGuardService,i43.AdminAuthGuardService]},
                    {path:'admin/products',component:i66.AdminProductsComponent,canActivate:[i37.AuthGuardService,
                        i43.AdminAuthGuardService]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hZG1pbi9hZG1pbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9hZG1pbi9hZG1pbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
