/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.nav-link.dropdown-toggle[_ngcontent-%COMP%] {\r\n  cursor: pointer;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9jb3JlL2NvbXBvbmVudHMvYnMtbmF2YmFyL2JzLW5hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvY29yZS9jb21wb25lbnRzL2JzLW5hdmJhci9icy1uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
