/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9zaG9wcGluZy9jb21wb25lbnRzL2NoZWNrLW91dC9jaGVjay1vdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9vcmdhbmljLXNob3AtbWFzdGVyL29yZ2FuaWMtc2hvcC9zcmMvYXBwL3Nob3BwaW5nL2NvbXBvbmVudHMvY2hlY2stb3V0L2NoZWNrLW91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
