/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './core.module';
import * as i2 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as i3 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as i4 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as i5 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as i6 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as i7 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as i8 from '../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as i9 from './components/login/login.component.ngfactory';
import * as i10 from '@angular/common';
import * as i11 from '@angular/forms';
import * as i12 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as i13 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as i14 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as i15 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as i16 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as i17 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as i18 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as i19 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as i20 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as i21 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as i22 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as i23 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as i24 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as i25 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as i26 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as i27 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as i28 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as i29 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as i30 from 'angularfire2';
import * as i31 from 'angularfire2/auth';
import * as i32 from 'angularfire2/database';
import * as i33 from '../shared/services/user.service';
import * as i34 from '../shared/services/auth.service';
import * as i35 from '../shared/services/auth-guard.service';
import * as i36 from '@angular/router';
import * as i37 from '../shared/services/category.service';
import * as i38 from '../shared/services/product.service';
import * as i39 from '../shared/services/shopping-cart.service';
import * as i40 from '../shared/services/order.service';
import * as i41 from 'ng2-validation/dist/index';
import * as i42 from 'angular-4-data-table/src/index';
import * as i43 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as i44 from '@ng-bootstrap/ng-bootstrap/buttons/buttons.module';
import * as i45 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as i46 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as i47 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as i48 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as i49 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as i50 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as i51 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as i52 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as i53 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as i54 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as i55 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as i56 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as i57 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as i58 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as i59 from '@ng-bootstrap/ng-bootstrap/index';
import * as i60 from '../shared/shared.module';
import * as i61 from './components/login/login.component';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.NgbAlertNgFactory,i3.NgbTooltipWindowNgFactory,i4.NgbTypeaheadWindowNgFactory,
              i5.NgbDatepickerNgFactory,i6.NgbModalBackdropNgFactory,i7.NgbModalWindowNgFactory,
              i8.NgbPopoverWindowNgFactory,i9.LoginComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i10.NgLocalization,i10.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i11.ɵi,i11.ɵi,([] as any[])),i0.ɵmpd(4608,i12.NgbModalStack,
          i12.NgbModalStack,[i0.ApplicationRef,i0.Injector,i0.ComponentFactoryResolver]),
          i0.ɵmpd(4608,i13.NgbModal,i13.NgbModal,[i0.ComponentFactoryResolver,i0.Injector,
              i12.NgbModalStack]),i0.ɵmpd(4608,i14.NgbAlertConfig,i14.NgbAlertConfig,
              ([] as any[])),i0.ɵmpd(4608,i15.NgbProgressbarConfig,i15.NgbProgressbarConfig,
              ([] as any[])),i0.ɵmpd(4608,i16.NgbTooltipConfig,i16.NgbTooltipConfig,
              ([] as any[])),i0.ɵmpd(4608,i17.NgbTypeaheadConfig,i17.NgbTypeaheadConfig,
              ([] as any[])),i0.ɵmpd(4608,i18.NgbAccordionConfig,i18.NgbAccordionConfig,
              ([] as any[])),i0.ɵmpd(4608,i19.NgbCarouselConfig,i19.NgbCarouselConfig,
              ([] as any[])),i0.ɵmpd(4608,i20.NgbCalendar,i20.NgbCalendarGregorian,
              ([] as any[])),i0.ɵmpd(4608,i21.NgbDatepickerI18n,i21.NgbDatepickerI18nDefault,
              ([] as any[])),i0.ɵmpd(4608,i22.NgbDateParserFormatter,i22.NgbDateISOParserFormatter,
              ([] as any[])),i0.ɵmpd(4608,i23.NgbDatepickerConfig,i23.NgbDatepickerConfig,
              ([] as any[])),i0.ɵmpd(4608,i24.NgbDropdownConfig,i24.NgbDropdownConfig,
              ([] as any[])),i0.ɵmpd(4608,i25.NgbPaginationConfig,i25.NgbPaginationConfig,
              ([] as any[])),i0.ɵmpd(4608,i26.NgbPopoverConfig,i26.NgbPopoverConfig,
              ([] as any[])),i0.ɵmpd(4608,i27.NgbRatingConfig,i27.NgbRatingConfig,
              ([] as any[])),i0.ɵmpd(4608,i28.NgbTabsetConfig,i28.NgbTabsetConfig,
              ([] as any[])),i0.ɵmpd(4608,i29.NgbTimepickerConfig,i29.NgbTimepickerConfig,
              ([] as any[])),i0.ɵmpd(5120,i30.FirebaseApp,i30.ɵa,[i30.FirebaseAppConfigToken,
              i30.FirebaseAppName]),i0.ɵmpd(5120,i31.AngularFireAuth,i31._getAngularFireAuth,
              [i30.FirebaseApp]),i0.ɵmpd(5120,i32.AngularFireDatabase,i32._getAngularFireDatabase,
              [i30.FirebaseApp]),i0.ɵmpd(4608,i33.UserService,i33.UserService,[i32.AngularFireDatabase]),
          i0.ɵmpd(4608,i34.AuthService,i34.AuthService,[i33.UserService,i31.AngularFireAuth]),
          i0.ɵmpd(4608,i35.AuthGuardService,i35.AuthGuardService,[i34.AuthService,
              i36.Router]),i0.ɵmpd(4608,i37.CategoryService,i37.CategoryService,[i32.AngularFireDatabase]),
          i0.ɵmpd(4608,i38.ProductService,i38.ProductService,[i32.AngularFireDatabase]),
          i0.ɵmpd(4608,i39.ShoppingCartService,i39.ShoppingCartService,[i32.AngularFireDatabase]),
          i0.ɵmpd(4608,i40.OrderService,i40.OrderService,[i32.AngularFireDatabase,
              i39.ShoppingCartService]),i0.ɵmpd(512,i10.CommonModule,i10.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i36.RouterModule,i36.RouterModule,[[2,i36.ɵa],
              [2,i36.Router]]),i0.ɵmpd(512,i11.ɵba,i11.ɵba,([] as any[])),i0.ɵmpd(512,
              i11.FormsModule,i11.FormsModule,([] as any[])),i0.ɵmpd(512,i41.CustomFormsModule,
              i41.CustomFormsModule,([] as any[])),i0.ɵmpd(512,i42.DataTableModule,
              i42.DataTableModule,([] as any[])),i0.ɵmpd(512,i43.NgbAlertModule,i43.NgbAlertModule,
              ([] as any[])),i0.ɵmpd(512,i44.NgbButtonsModule,i44.NgbButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i45.NgbCollapseModule,i45.NgbCollapseModule,
              ([] as any[])),i0.ɵmpd(512,i46.NgbProgressbarModule,i46.NgbProgressbarModule,
              ([] as any[])),i0.ɵmpd(512,i47.NgbTooltipModule,i47.NgbTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i48.NgbTypeaheadModule,i48.NgbTypeaheadModule,
              ([] as any[])),i0.ɵmpd(512,i49.NgbAccordionModule,i49.NgbAccordionModule,
              ([] as any[])),i0.ɵmpd(512,i50.NgbCarouselModule,i50.NgbCarouselModule,
              ([] as any[])),i0.ɵmpd(512,i51.NgbDatepickerModule,i51.NgbDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i52.NgbDropdownModule,i52.NgbDropdownModule,
              ([] as any[])),i0.ɵmpd(512,i53.NgbModalModule,i53.NgbModalModule,([] as any[])),
          i0.ɵmpd(512,i54.NgbPaginationModule,i54.NgbPaginationModule,([] as any[])),
          i0.ɵmpd(512,i55.NgbPopoverModule,i55.NgbPopoverModule,([] as any[])),i0.ɵmpd(512,
              i56.NgbRatingModule,i56.NgbRatingModule,([] as any[])),i0.ɵmpd(512,i57.NgbTabsetModule,
              i57.NgbTabsetModule,([] as any[])),i0.ɵmpd(512,i58.NgbTimepickerModule,
              i58.NgbTimepickerModule,([] as any[])),i0.ɵmpd(512,i59.NgbRootModule,
              i59.NgbRootModule,([] as any[])),i0.ɵmpd(512,i30.AngularFireModule,i30.AngularFireModule,
              ([] as any[])),i0.ɵmpd(512,i31.AngularFireAuthModule,i31.AngularFireAuthModule,
              ([] as any[])),i0.ɵmpd(512,i32.AngularFireDatabaseModule,i32.AngularFireDatabaseModule,
              ([] as any[])),i0.ɵmpd(512,i60.SharedModule,i60.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.CoreModule,i1.CoreModule,([] as any[])),i0.ɵmpd(1024,i36.ROUTES,
              () => {
                return [[{path:'login',component:i61.LoginComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovb3JnYW5pYy1zaG9wLW1hc3Rlci9vcmdhbmljLXNob3Avc3JjL2FwcC9jb3JlL2NvcmUubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L29yZ2FuaWMtc2hvcC1tYXN0ZXIvb3JnYW5pYy1zaG9wL3NyYy9hcHAvY29yZS9jb3JlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
